server:
  port: 8002
spring:
  application:
    name: rest-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.3:3306/test?serverTimeZone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_empty
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.3:7001/eureka/,http://192.168.1.3:7002/eureka/
  instance:
    prefer-ip-address: true
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: true
logging:
  level:
    com:
      springcloud: debug
