spring:
  application:
    name: register-second
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.3:7001/eureka/
  instance:
    prefer-ip-address: true
  server:
    #是否开启自我保护模式，默认为true。
    enable-self-preservation: true
server:
  port: 7002
