spring:
  application:
    name: door-first
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.3:7001/eureka/,http://192.168.1.3:7002/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
server:
  port: 8007
