server:
  port: 7001
spring:
  application:
    name: register-main
eureka:
  server:
    #是否开启自我保护模式，默认为true。
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://192.168.1.3:7002/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: true
